<h1>F.A.Q.&acute;s (provided by earthlab.com)</h1>
<h2>How is carbon increasing global warming?</h2>
<p>Carbon itself is not the problem. Carbon dioxide is … and not just carbon dioxide as it’s found in nature, but excessive amounts of carbon dioxide pumped into the atmosphere from human-related activities. Carbon dioxide, or CO2, in excessive amounts increases the size of the temperature-regulating “blanket” (mentioned in an earlier FAQ) surrounding the earth. This causes the surface temperature of the Earth to rise unnaturally, which as a result, increases global warming effects.</p>

<h2>How hot is it going to get?</h2>
<p>Too hot. The latest report from the Intergovernmental Panel on Climate Change projects that Earth’s average surface temperature will increase from 2.5&deg; to 10.4&deg;F (or 1.4&deg; to 5.8&deg;C) during the period between 1990 and 2100. That’s decidedly enough of a temperature increase to create some serious environmental consequences, including mass extinctions of innumerable plant and animal and animal species.</p>

<h2>But it was cold last month; what gives?</h2>
<p>Sure, and you may have had unusual snowfall in your hometown last year. But there is a clear distinction that must be drawn between weather and climate change (See FAQ above), and how the two affect each other. Although global warming uses the word “warming,” it’s important to remember that the phenomenon of global warming causes climate change, and as a result, creates unnatural weather patterns that can create harsher winter weather in some parts of the world. None of these phenomena are mutually exclusive, but rather highly interconnected and affect each other greatly.</p>

<h2>Hotter weather sounds good; what’s the problem with climate change?</h2>
<p>Well, it might sound good if you’re living in London and want a reprieve from dreary weather and rainfall, but you would likely change your tune if the waters were to come roaring down the Thames at a level higher than the barriers. Argue all you want, but glaciers are melting, oceans are rising, and storms are becoming increasingly worse. Many plant and animal species are highly temperature-sensitive, and as a result of unnaturally changing temperatures, they are being subject to extinction on a mass scale. Dramatic changes in weather patterns, like the one’s we’ve been experiencing in recent years, will likely trigger more severe storms, cyclones, and hurricanes. Last, but certainly not least, coastal and low-lying areas could be inundated by rising waters, as other areas around the world are stricken by severe and unnatural drought conditions. Hotter weather still sound good? </p>

<p class="multiple_pages">View F.A.Q.&acute;s from Earthlab.com: <a href="<?=$faqLnk1?>">1</a>, <a href="<?=$faqLnk2?>">2</a>, <a href="<?=$faqLnk3?>">3</a></p>